.TH "/home/jeroen/Programming/C++/Apherous/src Directory Reference" 3 "Sun Sep 27 2015" "Apherous" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jeroen/Programming/C++/Apherous/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaudio_mgr\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaudio_mgr\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBui_gtk\&.cpp\fP"
.br
.ti -1c
.RI "file \fBui_gtk\&.h\fP"
.br
.in -1c
