.TH "gtkInterface" 3 "Sun Sep 27 2015" "Apherous" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtkInterface \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBrun\fP (int argc, char **argv)"
.br
.RI "\fISets up the interface for running\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Gtk::Window * \fBwindow\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int gtkInterface::run (int argc, char ** argv)"

.PP
Sets up the interface for running\&. This function sets up the interface so it can be used in the GMainLoop
.PP
\fBParameters:\fP
.RS 4
\fIint\fP argc: Holds the total number of arguments passed to the function 
.br
\fIchar\fP **argv: Holda the arguments passed to the function 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Apherous from the source code\&.
